# Generated by Django 3.1.4 on 2020-12-19 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersauth', '0002_auto_20201219_2112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wu_user',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
